graphql.packages: com.pengrl.mind.zip.service

spring:
  datasource:
    url: jdbc:mysql://rm-uf68ea46v74l36g67.mysql.rds.aliyuncs.com:3306/green?useUnicode=true
    username: versa
    password: ZmnRZhvy7iTnVjl
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource